list(include('layer'))

---
# TODO: Consider renaming file_type to "output_file_type" or something --
# currently this is used when adding layers to the project file, so we should
# consider this as output_file_type and use a new key for source file type.

layer:
  # Used for unique identification, e.g. config, filenames.
  id: str()
  # Reference to a data source in datasets.yml (`{dataset_id}.{source_id}`)
  data_source: str()
  # The index of a task enumerated in qgreenland.tasks.layers.ingest_tasks
  # TODO: Validate that `ingest_task` is member of INGEST_TASKS
  ingest_task: str()
  ingest_task_kwargs: map(required=False)
  unzip_kwargs: include('unzip_kwargs', required=False)
  # The file extension, e.g. '.shp'
  file_type: str()
  data_type: enum('vector', 'raster')
  # Short descriptive text, e.g. the layer name in QGIS.
  title: str()
  # The fully-qualified QGIS group the layer should be placed in, e.g.
  # 'Group/Subgroup/Subsubgroup'
  group_path: str()
  # The name of a style (represented as .qml file in `assets/styles`). Should
  # NOT include .qml file extension
  style: str(required=False)
  subset_kwargs: include('subset_kwargs', required=False)
  overviews_kwargs: include('overviews_kwargs', required=False)
  warp_kwargs: include('warp_kwargs', required=False)
  # Is this layer initially "checked" as visible in QGIS?
  visible: bool()
  # Sometimes, the source data may not come with projection metadata, or the
  # metadta may be wrong. Override the layer projection with this key. E.g.,
  # `EPSG:3321`.
  override_source_projection: str(required=False)

---
overviews_kwargs:
  # Keyword arguments to rasterio `dataset.build_overviews()` method
  overview_levels: list(int())
  resampling_method: str()

---
warp_kwargs:
  # Keyword arguments to gdal.Warp method
  xRes: int(required=False)
  yRes: int(required=False)
  warpOptions: list(str(), required=False)

---
subset_kwargs:
  # A bounding box dictionary. NOTE: The order of this dictionary is important
  # for passing to qgc.QgsRectangle
  xmin: num()
  ymin: num()
  xmax: num()
  ymax: num()

---
unzip_kwargs:
  # Keyword arguments to gdal.Warp method
  default_filename_pattern: str(required=False)
