################
# Science Data #
################

# - &glacier_terminus
#   id: glacier_terminus_glacier_ids
#   data_source: glacier_terminus.glacier_ids
#   ingest_task: glacier_terminus
#   title: 'Glacier IDs'
#   file_type: '.shp'
#   data_type: 'vector'
#   group_path: 'Glaciology/Glacier Terminus'
#   visible: True
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2000_2001
#   data_source: glacier_terminus.2000_2001
#   title: 'Glacier Termini 2000 to 2001'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2005_2006
#   data_source: glacier_terminus.2005_2006
#   title: 'Glacier Termini 2005 to 2006'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2006_2007
#   data_source: glacier_terminus.2006_2007
#   title: 'Glacier Termini 2006 to 2007'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2007_2008
#   data_source: glacier_terminus.2007_2008
#   title: 'Glacier Termini 2007 to 2008'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2008_2009
#   data_source: glacier_terminus.2008_2009
#   title: 'Glacier Termini 2008 to 2009'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2012_2013
#   data_source: glacier_terminus.2012_2013
#   title: 'Glacier Termini 2012 to 2013'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2014_2015
#   data_source: glacier_terminus.2014_2015
#   title: 'Glacier Termini 2014 to 2015'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2015_2016
#   data_source: glacier_terminus.2015_2016
#   title: 'Glacier Termini 2015 to 2016'
# 
# 
# - <<: *glacier_terminus
#   id: glacier_terminus_2016_2017
#   data_source: glacier_terminus.2016_2017
#   title: 'Glacier Termini 2016 to 2017'
# 
# 
# - id: velocity_mosaic
#   data_source: velocity_mosaic.only
#   ingest_task: velocity_mosaic
#   ingest_task_kwargs: {'extract_dataset': 'v'}
#   file_type: '.tif'
#   data_type: 'raster'
#   title: 'Ice Sheet Velocity'
#   style: 'ice_sheet_velocity'
#   overviews_kwargs:
#     overview_levels: [2, 4, 8, 16]
#     resampling_method: average
#   warp_kwargs:
#     xRes: 500
#     yRes: 500
#   visible: True
#   # TODO: Does this count as glaciology?
#   group_path: 'Cryosphere/Ice Sheet Velocity'
# 
# 
# - &bedmachine
#   id: bedmachine_bed
#   data_source: bedmachine.only
#   ingest_task: bedmachine
#   ingest_task_kwargs: {'extract_dataset': 'bed'}
#   file_type: '.tif'
#   data_type: 'raster'
#   title: 'Bedrock Elevation'
#   style: 'bedmachine_bed'
#   warp_kwargs:
#     xRes: 1000
#     yRes: 1000
#   visible: True
#   group_path: 'Geophysics/IceBridge BedMachine'
# 
# 
# - <<: *bedmachine
#   id: bedmachine_surface
#   ingest_task_kwargs: {'extract_dataset': 'surface'}
#   title: 'Surface Elevation'
#   style: null
#   visible: False
# 
# 
# - <<: *bedmachine
#   id: bedmachine_thickness
#   ingest_task_kwargs: {'extract_dataset': 'thickness'}
#   title: 'Ice Thickness'
#   style: null
#   visible: False
# 
# 
# - id: hydrologic_subbasins
#   data_source: hydrologic_subbasins.only
#   ingest_task: rarred_shapefile
#   file_type: '.shp'
#   data_type: 'vector'
#   title: 'Hydrologic Sub-Basins'
#   visible: False
#   group_path: 'Hydrology'
#   override_source_projection: 'ESRI:102018'
# 
# 
# ############
# # BASEMAPS #
# ############
# 
# 
# - id: populated_places
#   data_source: populated_places.only
#   ingest_task: zipped_shapefile
#   file_type: '.shp'
#   data_type: 'vector'
#   title: 'Populated Places'
#   # style: 'populated_places'
#   subset_kwargs:
#     xmin: -796814.1
#     ymin: -322934.6
#     xmax: 1103185.9
#     ymax: -3599419.2
#   # TODO: Enable a style with labels for placenames, make visible again
#   visible: False
#   group_path: 'Basemaps'
# 
# 
# - id: coastlines
#   data_source: coastlines.only
#   ingest_task: zipped_shapefile
#   file_type: '.shp'
#   data_type: 'vector'
#   title: 'Coastlines'
#   visible: False
#   group_path: 'Basemaps'
# 
# 
# # NOTE: We attempted to add the corresponding NE Ocean layer, but it included
# # holes for small islands which are not present on the land layer, and that was
# # gross so we removed the ocean layer.
# - id: land
#   data_source: land_shape.only
#   ingest_task: zipped_shapefile
#   file_type: '.shp'
#   data_type: 'vector'
#   title: 'Land'
#   style: 'land'
#   visible: True
#   group_path: 'Basemaps'
# 
# 
# - id: arctic_dem
#   data_source: arctic_dem.only
#   ingest_task: arctic_dem
#   file_type: '.tif'
#   data_type: 'raster'
#   title: 'Arctic DEM (1km mosaic)'
#   style: 'arctic_dem'
#   overviews_kwargs:
#     overview_levels: [2, 4, 8, 16]
#     resampling_method: average
#   visible: False
#   group_path: 'Basemaps'
# 
# 
# - id: background
#   data_source: background.only
#   ingest_task: background_image
#   file_type: '.tif'
#   data_type: 'raster'
#   title: 'Background'
#   # NOTE: Without passing warp_kwargs, we get a black image.
#   # TODO: Which of these args are necessary to avoid that?
#   warp_kwargs:
#     xRes: 1000
#     yRes: 1000
#     # Attempt to avoid pole hole and nodata line where east and west edges of
#     # the original image meet after polar wrapping. TODO: This doesn't actually
#     # get rid of the line.
#     warpOptions: ['SOURCE_EXTRA=100', 'SAMPLE_GRID=YES']
#   visible: True
#   group_path: 'Basemaps'
# 
# 
# - id: common_murre_colonies
#   data_source: murre_colonies.only
#   ingest_task: common_murre_colonies
#   unzip_kwargs:
#     default_filename_pattern: '^Distribution_Common_Murre_colonies.*'
#   file_type: '.tif'
#   data_type: 'raster'
#   title: 'Distribution of Common Murre Colonies'
#   visible: False
#   group_path: 'Birds'


- id: thick_billed_murre_colonies
  data_source: murre_colonies.only
  ingest_task: thick_billed_murre_colonies
  unzip_kwargs:
    default_filename_pattern: '^Distribution_Thickbilled_Murre_colonies.*'
  file_type: '.tif'
  data_type: 'raster'
  title: 'Distribution of Common Murre Colonies'
  visible: False
  group_path: 'Birds'
